"""
Database initialization script for Trend Hunter
Creates SQLite database with all required tables
"""

import sqlite3
import os
from pathlib import Path
from datetime import datetime


class DatabaseInitializer:
    def __init__(self, db_path="data/trendhunter.db"):
        self.db_path = db_path
        # Ensure data directory exists
        Path(db_path).parent.mkdir(parents=True, exist_ok=True)
        
    def connect(self):
        """Create database connection"""
        return sqlite3.connect(self.db_path)
    
    def create_tables(self):
        """Create all required tables"""
        conn = self.connect()
        cursor = conn.cursor()
        
        try:
            # Table 1: sources_raw - Raw data from crawlers
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS sources_raw (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    source TEXT NOT NULL,  -- 'reddit', 'tiktok', etc.
                    platform_id TEXT,  -- Original post/content ID from platform
                    author TEXT,
                    title TEXT,
                    text TEXT,
                    url TEXT,
                    score INTEGER,  -- Upvotes/likes
                    comments_count INTEGER,
                    meta_json TEXT,  -- Additional metadata in JSON format
                    created_at DATETIME,
                    inserted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE(source, platform_id)
                )
            """)
            
            # Table 2: keywords - Canonical terms and their variants
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS keywords (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    canonical_term TEXT NOT NULL UNIQUE,
                    variants_json TEXT,  -- JSON array of spelling variants
                    category TEXT,  -- Optional categorization
                    first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    last_seen DATETIME,
                    total_mentions INTEGER DEFAULT 0,
                    is_active BOOLEAN DEFAULT 1,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME
                )
            """)
            
            # Table 3: time_series_metrics - Google Trends and platform metrics over time
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS time_series_metrics (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    term_id INTEGER NOT NULL,
                    date_time DATETIME NOT NULL,
                    iot_value REAL,  -- Interest Over Time from Google Trends
                    mentions_reddit INTEGER DEFAULT 0,
                    mentions_tiktok INTEGER DEFAULT 0,
                    mentions_total INTEGER DEFAULT 0,
                    platform_count INTEGER DEFAULT 0,  -- Number of platforms term appears on
                    raw_samples_json TEXT,  -- Raw replicate samples from pytrends
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (term_id) REFERENCES keywords(id),
                    UNIQUE(term_id, date_time)
                )
            """)
            
            # Table 4: features - Computed features for scoring
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS features (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    term_id INTEGER NOT NULL,
                    date_time DATETIME NOT NULL,
                    slope REAL,  -- Trend slope
                    acceleration REAL,  -- Rate of change of slope
                    ma3 REAL,  -- 3-day moving average
                    ma7 REAL,  -- 7-day moving average
                    pct_change_24h REAL,  -- 24-hour percentage change
                    novelty_score REAL,  -- How new/unique the term is
                    influencer_weighted_mentions REAL,  -- Mentions weighted by author influence
                    velocity REAL,  -- Speed of trend growth
                    volatility REAL,  -- Variance in mentions/IOT
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (term_id) REFERENCES keywords(id),
                    UNIQUE(term_id, date_time)
                )
            """)
            
            # Table 5: flags - Trend flags/alerts generated by scoring engine
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS flags (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    term_id INTEGER NOT NULL,
                    date_time DATETIME NOT NULL,
                    trend_score REAL NOT NULL,
                    label TEXT NOT NULL,  -- 'Hidden Gem', 'Breakout', 'Stable', 'Dying'
                    confidence REAL,  -- Confidence level 0-1
                    reason_codes TEXT,  -- JSON array of reasons for flagging
                    alert_sent BOOLEAN DEFAULT 0,
                    alert_sent_at DATETIME,
                    is_verified BOOLEAN,  -- Manual verification status
                    verified_at DATETIME,
                    notes TEXT,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (term_id) REFERENCES keywords(id)
                )
            """)
            
            # Table 6: ground_truth - Manual labels for backtest/training
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS ground_truth (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    term_id INTEGER NOT NULL,
                    flag_date DATETIME NOT NULL,
                    outcome_date DATETIME,
                    is_true_trend BOOLEAN,  -- Did it actually become a trend?
                    peak_iot REAL,  -- Peak IOT value achieved
                    peak_date DATETIME,
                    lead_time_hours REAL,  -- Hours from flag to peak
                    notes TEXT,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at DATETIME,
                    FOREIGN KEY (term_id) REFERENCES keywords(id)
                )
            """)
            
            # Table 7: jobs_log - Scheduler/job execution log
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS jobs_log (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    job_name TEXT NOT NULL,
                    job_type TEXT,  -- 'crawler', 'processing', 'scoring', etc.
                    status TEXT NOT NULL,  -- 'started', 'completed', 'failed'
                    start_time DATETIME NOT NULL,
                    end_time DATETIME,
                    duration_seconds REAL,
                    items_processed INTEGER,
                    error_message TEXT,
                    meta_json TEXT,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            
            # Table 8: cache - Simple key-value cache for API responses
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS cache (
                    key TEXT PRIMARY KEY,
                    value TEXT NOT NULL,
                    expires_at DATETIME NOT NULL,
                    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            
            # Create indexes for better query performance
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_sources_timestamp ON sources_raw(timestamp)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_sources_source ON sources_raw(source)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_keywords_canonical ON keywords(canonical_term)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_timeseries_term_date ON time_series_metrics(term_id, date_time)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_features_term_date ON features(term_id, date_time)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_flags_term_date ON flags(term_id, date_time)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_flags_score ON flags(trend_score)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_flags_label ON flags(label)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_jobs_name ON jobs_log(job_name)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_jobs_status ON jobs_log(status)")
            cursor.execute("CREATE INDEX IF NOT EXISTS idx_cache_expires ON cache(expires_at)")
            
            conn.commit()
            print("✅ Database tables created successfully!")
            
            # Print table summary
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
            tables = cursor.fetchall()
            print(f"\n📊 Created {len(tables)} tables:")
            for table in tables:
                print(f"   - {table[0]}")
                
        except sqlite3.Error as e:
            print(f"❌ Error creating tables: {e}")
            conn.rollback()
            raise
        finally:
            conn.close()
    
    def verify_schema(self):
        """Verify all tables exist"""
        conn = self.connect()
        cursor = conn.cursor()
        
        expected_tables = [
            'sources_raw', 'keywords', 'time_series_metrics', 
            'features', 'flags', 'ground_truth', 'jobs_log', 'cache'
        ]
        
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
        existing_tables = [row[0] for row in cursor.fetchall()]
        
        missing = set(expected_tables) - set(existing_tables)
        if missing:
            print(f"⚠️  Missing tables: {missing}")
            return False
        
        print("✅ All required tables exist!")
        conn.close()
        return True
    
    def get_stats(self):
        """Get basic database statistics"""
        conn = self.connect()
        cursor = conn.cursor()
        
        stats = {}
        tables = ['sources_raw', 'keywords', 'time_series_metrics', 'features', 'flags']
        
        for table in tables:
            cursor.execute(f"SELECT COUNT(*) FROM {table}")
            count = cursor.fetchone()[0]
            stats[table] = count
        
        conn.close()
        return stats


def main():
    """Main initialization function"""
    print("🚀 Initializing Trend Hunter Database...")
    print("=" * 50)
    
    # Initialize database
    db_init = DatabaseInitializer()
    
    # Create tables
    db_init.create_tables()
    
    # Verify schema
    print("\n🔍 Verifying schema...")
    if db_init.verify_schema():
        print("\n✅ Database initialization completed successfully!")
        print(f"📁 Database location: {os.path.abspath(db_init.db_path)}")
        
        # Show initial stats
        stats = db_init.get_stats()
        print("\n📊 Initial record counts:")
        for table, count in stats.items():
            print(f"   {table}: {count}")
    else:
        print("\n❌ Database initialization failed!")
        return 1
    
    print("\n" + "=" * 50)
    print("🎉 Ready to start crawling!")
    return 0


if __name__ == "__main__":
    exit(main())
